import type { Warga, KartuKeluarga, Transaksi, User } from "./types"

export const RW_NUMBER = "05"
export const RT_LIST = ["01", "02", "03", "04", "05"]

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    username: "superadmin",
    nama: "Bapak Sutrisno",
    role: "super-admin",
    rw: RW_NUMBER,
  },
  {
    id: "u2",
    username: "admin01",
    nama: "Bapak Hartono",
    role: "admin",
    rt: "01",
    rw: RW_NUMBER,
  },
  {
    id: "u3",
    username: "admin02",
    nama: "Bapak Wibowo",
    role: "admin",
    rt: "02",
    rw: RW_NUMBER,
  },
  {
    id: "u4",
    username: "warga",
    nama: "Andi Pratama",
    role: "warga",
    rt: "01",
    rw: RW_NUMBER,
    nik: "3201010101900001",
  },
]

export const MOCK_WARGA: Warga[] = [
  {
    id: "w1",
    nik: "3201010101900001",
    noKK: "3201010101900001",
    nama: "Andi Pratama",
    jenisKelamin: "Laki-laki",
    tempatLahir: "Jakarta",
    tanggalLahir: "1990-01-01",
    agama: "Islam",
    pendidikan: "S1",
    pekerjaan: "Karyawan Swasta",
    pendapatan: 8500000,
    statusPerkawinan: "Kawin",
    hubunganKeluarga: "Kepala Keluarga",
    kewarganegaraan: "WNI",
    alamat: "Jl. Melati No. 12",
    rt: "01",
    rw: "05",
    statusKependudukan: "Tetap",
    noTelepon: "081234567890",
    email: "andi.pratama@example.com",
  },
  {
    id: "w2",
    nik: "3201010102920002",
    noKK: "3201010101900001",
    nama: "Siti Nurhaliza",
    jenisKelamin: "Perempuan",
    tempatLahir: "Bandung",
    tanggalLahir: "1992-05-15",
    agama: "Islam",
    pendidikan: "S1",
    pekerjaan: "Ibu Rumah Tangga",
    pendapatan: 0,
    statusPerkawinan: "Kawin",
    hubunganKeluarga: "Istri",
    kewarganegaraan: "WNI",
    alamat: "Jl. Melati No. 12",
    rt: "01",
    rw: "05",
    statusKependudukan: "Tetap",
    noTelepon: "081234567891",
  },
  {
    id: "w3",
    nik: "3201010103150003",
    noKK: "3201010101900001",
    nama: "Rafa Pratama",
    jenisKelamin: "Laki-laki",
    tempatLahir: "Jakarta",
    tanggalLahir: "2015-08-20",
    agama: "Islam",
    pendidikan: "SD",
    pekerjaan: "Pelajar",
    pendapatan: 0,
    statusPerkawinan: "Belum Kawin",
    hubunganKeluarga: "Anak",
    kewarganegaraan: "WNI",
    alamat: "Jl. Melati No. 12",
    rt: "01",
    rw: "05",
    statusKependudukan: "Tetap",
  },
  {
    id: "w4",
    nik: "3201010104850004",
    noKK: "3201010104850004",
    nama: "Budi Santoso",
    jenisKelamin: "Laki-laki",
    tempatLahir: "Surabaya",
    tanggalLahir: "1985-03-10",
    agama: "Kristen",
    pendidikan: "S2",
    pekerjaan: "Dokter",
    pendapatan: 18000000,
    statusPerkawinan: "Kawin",
    hubunganKeluarga: "Kepala Keluarga",
    kewarganegaraan: "WNI",
    alamat: "Jl. Mawar No. 8",
    rt: "01",
    rw: "05",
    statusKependudukan: "Tetap",
    noTelepon: "081234567892",
    email: "budi.santoso@example.com",
  },
  {
    id: "w5",
    nik: "3201010105870005",
    noKK: "3201010104850004",
    nama: "Linda Santoso",
    jenisKelamin: "Perempuan",
    tempatLahir: "Surabaya",
    tanggalLahir: "1987-07-22",
    agama: "Kristen",
    pendidikan: "S1",
    pekerjaan: "Guru",
    pendapatan: 6500000,
    statusPerkawinan: "Kawin",
    hubunganKeluarga: "Istri",
    kewarganegaraan: "WNI",
    alamat: "Jl. Mawar No. 8",
    rt: "01",
    rw: "05",
    statusKependudukan: "Tetap",
  },
  {
    id: "w6",
    nik: "3201010106950006",
    noKK: "3201010106950006",
    nama: "Dewi Lestari",
    jenisKelamin: "Perempuan",
    tempatLahir: "Yogyakarta",
    tanggalLahir: "1995-11-12",
    agama: "Islam",
    pendidikan: "S1",
    pekerjaan: "Wiraswasta",
    pendapatan: 12000000,
    statusPerkawinan: "Belum Kawin",
    hubunganKeluarga: "Kepala Keluarga",
    kewarganegaraan: "WNI",
    alamat: "Jl. Anggrek No. 5",
    rt: "02",
    rw: "05",
    statusKependudukan: "Domisili",
    noTelepon: "081234567893",
    email: "dewi.lestari@example.com",
  },
  {
    id: "w7",
    nik: "3201010107880007",
    noKK: "3201010107880007",
    nama: "Joko Widodo",
    jenisKelamin: "Laki-laki",
    tempatLahir: "Solo",
    tanggalLahir: "1988-04-05",
    agama: "Islam",
    pendidikan: "S1",
    pekerjaan: "PNS",
    pendapatan: 9500000,
    statusPerkawinan: "Kawin",
    hubunganKeluarga: "Kepala Keluarga",
    kewarganegaraan: "WNI",
    alamat: "Jl. Kenanga No. 21",
    rt: "02",
    rw: "05",
    statusKependudukan: "Tetap",
    noTelepon: "081234567894",
  },
  {
    id: "w8",
    nik: "3201010108910008",
    noKK: "3201010107880007",
    nama: "Maya Widodo",
    jenisKelamin: "Perempuan",
    tempatLahir: "Solo",
    tanggalLahir: "1991-09-18",
    agama: "Islam",
    pendidikan: "D3",
    pekerjaan: "Perawat",
    pendapatan: 5500000,
    statusPerkawinan: "Kawin",
    hubunganKeluarga: "Istri",
    kewarganegaraan: "WNI",
    alamat: "Jl. Kenanga No. 21",
    rt: "02",
    rw: "05",
    statusKependudukan: "Tetap",
  },
  {
    id: "w9",
    nik: "3201010109930009",
    noKK: "3201010109930009",
    nama: "Rian Hidayat",
    jenisKelamin: "Laki-laki",
    tempatLahir: "Bogor",
    tanggalLahir: "1993-06-30",
    agama: "Islam",
    pendidikan: "SMA",
    pekerjaan: "Karyawan Swasta",
    pendapatan: 5000000,
    statusPerkawinan: "Belum Kawin",
    hubunganKeluarga: "Kepala Keluarga",
    kewarganegaraan: "WNI",
    alamat: "Jl. Dahlia No. 14",
    rt: "03",
    rw: "05",
    statusKependudukan: "Kontrak",
    noTelepon: "081234567895",
  },
  {
    id: "w10",
    nik: "3201010110890010",
    noKK: "3201010110890010",
    nama: "Hadi Susanto",
    jenisKelamin: "Laki-laki",
    tempatLahir: "Semarang",
    tanggalLahir: "1989-12-25",
    agama: "Katolik",
    pendidikan: "S1",
    pekerjaan: "Engineer",
    pendapatan: 15000000,
    statusPerkawinan: "Kawin",
    hubunganKeluarga: "Kepala Keluarga",
    kewarganegaraan: "WNI",
    alamat: "Jl. Cempaka No. 7",
    rt: "03",
    rw: "05",
    statusKependudukan: "Tetap",
    email: "hadi.susanto@example.com",
  },
  {
    id: "w11",
    nik: "3201010111900011",
    noKK: "3201010110890010",
    nama: "Ratna Susanto",
    jenisKelamin: "Perempuan",
    tempatLahir: "Semarang",
    tanggalLahir: "1990-02-14",
    agama: "Katolik",
    pendidikan: "S1",
    pekerjaan: "Akuntan",
    pendapatan: 8000000,
    statusPerkawinan: "Kawin",
    hubunganKeluarga: "Istri",
    kewarganegaraan: "WNI",
    alamat: "Jl. Cempaka No. 7",
    rt: "03",
    rw: "05",
    statusKependudukan: "Tetap",
  },
  {
    id: "w12",
    nik: "3201010112940012",
    noKK: "3201010112940012",
    nama: "Agus Setiawan",
    jenisKelamin: "Laki-laki",
    tempatLahir: "Malang",
    tanggalLahir: "1994-10-08",
    agama: "Islam",
    pendidikan: "SMK",
    pekerjaan: "Wiraswasta",
    pendapatan: 6000000,
    statusPerkawinan: "Kawin",
    hubunganKeluarga: "Kepala Keluarga",
    kewarganegaraan: "WNI",
    alamat: "Jl. Flamboyan No. 3",
    rt: "04",
    rw: "05",
    statusKependudukan: "Tetap",
    noTelepon: "081234567896",
  },
  {
    id: "w13",
    nik: "3201010113960013",
    noKK: "3201010112940012",
    nama: "Sari Setiawan",
    jenisKelamin: "Perempuan",
    tempatLahir: "Malang",
    tanggalLahir: "1996-03-19",
    agama: "Islam",
    pendidikan: "SMA",
    pekerjaan: "Ibu Rumah Tangga",
    pendapatan: 0,
    statusPerkawinan: "Kawin",
    hubunganKeluarga: "Istri",
    kewarganegaraan: "WNI",
    alamat: "Jl. Flamboyan No. 3",
    rt: "04",
    rw: "05",
    statusKependudukan: "Tetap",
  },
  {
    id: "w14",
    nik: "3201010114820014",
    noKK: "3201010114820014",
    nama: "Bambang Wijaya",
    jenisKelamin: "Laki-laki",
    tempatLahir: "Jakarta",
    tanggalLahir: "1982-08-11",
    agama: "Islam",
    pendidikan: "S2",
    pekerjaan: "Manajer",
    pendapatan: 20000000,
    statusPerkawinan: "Kawin",
    hubunganKeluarga: "Kepala Keluarga",
    kewarganegaraan: "WNI",
    alamat: "Jl. Tulip No. 19",
    rt: "04",
    rw: "05",
    statusKependudukan: "Tetap",
    noTelepon: "081234567897",
    email: "bambang.wijaya@example.com",
  },
  {
    id: "w15",
    nik: "3201010115970015",
    noKK: "3201010115970015",
    nama: "Putri Ayu",
    jenisKelamin: "Perempuan",
    tempatLahir: "Bali",
    tanggalLahir: "1997-05-25",
    agama: "Hindu",
    pendidikan: "S1",
    pekerjaan: "Designer",
    pendapatan: 9000000,
    statusPerkawinan: "Belum Kawin",
    hubunganKeluarga: "Kepala Keluarga",
    kewarganegaraan: "WNI",
    alamat: "Jl. Sakura No. 11",
    rt: "05",
    rw: "05",
    statusKependudukan: "Domisili",
    noTelepon: "081234567898",
  },
  {
    id: "w16",
    nik: "3201010116860016",
    noKK: "3201010116860016",
    nama: "Rudi Hermawan",
    jenisKelamin: "Laki-laki",
    tempatLahir: "Bandung",
    tanggalLahir: "1986-01-30",
    agama: "Islam",
    pendidikan: "S1",
    pekerjaan: "Dosen",
    pendapatan: 11000000,
    statusPerkawinan: "Kawin",
    hubunganKeluarga: "Kepala Keluarga",
    kewarganegaraan: "WNI",
    alamat: "Jl. Mangga No. 6",
    rt: "05",
    rw: "05",
    statusKependudukan: "Tetap",
    noTelepon: "081234567899",
  },
  {
    id: "w17",
    nik: "3201010117880017",
    noKK: "3201010116860016",
    nama: "Yuni Hermawan",
    jenisKelamin: "Perempuan",
    tempatLahir: "Bandung",
    tanggalLahir: "1988-07-04",
    agama: "Islam",
    pendidikan: "S1",
    pekerjaan: "Bidan",
    pendapatan: 7000000,
    statusPerkawinan: "Kawin",
    hubunganKeluarga: "Istri",
    kewarganegaraan: "WNI",
    alamat: "Jl. Mangga No. 6",
    rt: "05",
    rw: "05",
    statusKependudukan: "Tetap",
  },
  {
    id: "w18",
    nik: "3201010118100018",
    noKK: "3201010116860016",
    nama: "Reza Hermawan",
    jenisKelamin: "Laki-laki",
    tempatLahir: "Jakarta",
    tanggalLahir: "2010-12-15",
    agama: "Islam",
    pendidikan: "SMP",
    pekerjaan: "Pelajar",
    pendapatan: 0,
    statusPerkawinan: "Belum Kawin",
    hubunganKeluarga: "Anak",
    kewarganegaraan: "WNI",
    alamat: "Jl. Mangga No. 6",
    rt: "05",
    rw: "05",
    statusKependudukan: "Tetap",
  },
  {
    id: "w19",
    nik: "3201010119920019",
    noKK: "3201010119920019",
    nama: "Eko Prasetyo",
    jenisKelamin: "Laki-laki",
    tempatLahir: "Surabaya",
    tanggalLahir: "1992-09-09",
    agama: "Islam",
    pendidikan: "SMA",
    pekerjaan: "Sopir",
    pendapatan: 4500000,
    statusPerkawinan: "Belum Kawin",
    hubunganKeluarga: "Kepala Keluarga",
    kewarganegaraan: "WNI",
    alamat: "Jl. Pinang No. 9",
    rt: "02",
    rw: "05",
    statusKependudukan: "Kontrak",
  },
  {
    id: "w20",
    nik: "3201010120950020",
    noKK: "3201010120950020",
    nama: "Nina Pertiwi",
    jenisKelamin: "Perempuan",
    tempatLahir: "Medan",
    tanggalLahir: "1995-04-17",
    agama: "Kristen",
    pendidikan: "S1",
    pekerjaan: "Marketing",
    pendapatan: 7500000,
    statusPerkawinan: "Belum Kawin",
    hubunganKeluarga: "Kepala Keluarga",
    kewarganegaraan: "WNI",
    alamat: "Jl. Jambu No. 4",
    rt: "04",
    rw: "05",
    statusKependudukan: "Domisili",
    noTelepon: "081234567800",
  },
]

export function getKartuKeluargaList(): KartuKeluarga[] {
  const kkMap = new Map<string, KartuKeluarga>()
  MOCK_WARGA.forEach((w) => {
    if (!kkMap.has(w.noKK)) {
      kkMap.set(w.noKK, {
        noKK: w.noKK,
        kepalaKeluarga: "",
        alamat: w.alamat,
        rt: w.rt,
        rw: w.rw,
        jumlahAnggota: 0,
        tanggalDibuat: "2020-01-15",
        anggota: [],
      })
    }
    const kk = kkMap.get(w.noKK)!
    kk.anggota.push(w)
    kk.jumlahAnggota = kk.anggota.length
    if (w.hubunganKeluarga === "Kepala Keluarga") {
      kk.kepalaKeluarga = w.nama
    }
  })
  return Array.from(kkMap.values())
}

export const MOCK_TRANSAKSI: Transaksi[] = [
  {
    id: "t1",
    tanggal: "2026-05-01",
    keterangan: "Iuran kas warga April",
    kategori: "Iuran Bulanan",
    jumlah: 4500000,
    jenis: "masuk",
    rt: "01",
    pencatat: "Bapak Hartono",
  },
  {
    id: "t2",
    tanggal: "2026-05-02",
    keterangan: "Iuran kas warga April",
    kategori: "Iuran Bulanan",
    jumlah: 3800000,
    jenis: "masuk",
    rt: "02",
    pencatat: "Bapak Wibowo",
  },
  {
    id: "t3",
    tanggal: "2026-05-03",
    keterangan: "Pembelian kebutuhan posyandu",
    kategori: "Kesehatan",
    jumlah: 1200000,
    jenis: "keluar",
    rt: "01",
    pencatat: "Bapak Hartono",
  },
  {
    id: "t4",
    tanggal: "2026-04-28",
    keterangan: "Donasi warga untuk kebersihan",
    kategori: "Donasi",
    jumlah: 2000000,
    jenis: "masuk",
    pencatat: "Bapak Sutrisno",
  },
  {
    id: "t5",
    tanggal: "2026-04-25",
    keterangan: "Pembayaran petugas kebersihan",
    kategori: "Operasional",
    jumlah: 1500000,
    jenis: "keluar",
    pencatat: "Bapak Sutrisno",
  },
  {
    id: "t6",
    tanggal: "2026-04-20",
    keterangan: "Iuran kas warga Maret",
    kategori: "Iuran Bulanan",
    jumlah: 4500000,
    jenis: "masuk",
    rt: "03",
    pencatat: "Bapak Surya",
  },
  {
    id: "t7",
    tanggal: "2026-04-15",
    keterangan: "Renovasi pos ronda",
    kategori: "Pembangunan",
    jumlah: 3500000,
    jenis: "keluar",
    rt: "04",
    pencatat: "Bapak Tono",
  },
  {
    id: "t8",
    tanggal: "2026-04-10",
    keterangan: "Iuran sampah bulanan",
    kategori: "Kebersihan",
    jumlah: 2800000,
    jenis: "masuk",
    rt: "05",
    pencatat: "Bapak Joko",
  },
  {
    id: "t9",
    tanggal: "2026-04-05",
    keterangan: "Acara 17 Agustus",
    kategori: "Kegiatan",
    jumlah: 5000000,
    jenis: "keluar",
    pencatat: "Bapak Sutrisno",
  },
  {
    id: "t10",
    tanggal: "2026-04-01",
    keterangan: "Iuran kas warga Februari",
    kategori: "Iuran Bulanan",
    jumlah: 4200000,
    jenis: "masuk",
    rt: "01",
    pencatat: "Bapak Hartono",
  },
]

export function getStatistikDemografi(rt?: string) {
  const filtered = rt ? MOCK_WARGA.filter((w) => w.rt === rt) : MOCK_WARGA
  return {
    total: filtered.length,
    tetap: filtered.filter((w) => w.statusKependudukan === "Tetap").length,
    domisili: filtered.filter((w) => w.statusKependudukan === "Domisili").length,
    kontrak: filtered.filter((w) => w.statusKependudukan === "Kontrak").length,
    lakiLaki: filtered.filter((w) => w.jenisKelamin === "Laki-laki").length,
    perempuan: filtered.filter((w) => w.jenisKelamin === "Perempuan").length,
  }
}

export function getStatistikKeuangan(rt?: string) {
  const filtered = rt ? MOCK_TRANSAKSI.filter((t) => t.rt === rt) : MOCK_TRANSAKSI
  const masuk = filtered.filter((t) => t.jenis === "masuk").reduce((s, t) => s + t.jumlah, 0)
  const keluar = filtered.filter((t) => t.jenis === "keluar").reduce((s, t) => s + t.jumlah, 0)
  return {
    masuk,
    keluar,
    saldo: masuk - keluar,
    transaksi: filtered,
  }
}

export function getSebaranRT() {
  return RT_LIST.map((rt) => ({
    rt: `RT ${rt}`,
    warga: MOCK_WARGA.filter((w) => w.rt === rt).length,
    kk: new Set(MOCK_WARGA.filter((w) => w.rt === rt).map((w) => w.noKK)).size,
  }))
}

export function formatRupiah(value: number): string {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
  }).format(value)
}

export function formatTanggal(date: string): string {
  return new Intl.DateTimeFormat("id-ID", {
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(new Date(date))
}

export function calculateAge(birthDate: string): number {
  const today = new Date()
  const birth = new Date(birthDate)
  let age = today.getFullYear() - birth.getFullYear()
  const m = today.getMonth() - birth.getMonth()
  if (m < 0 || (m === 0 && today.getDate() < birth.getDate())) {
    age--
  }
  return age
}
